#!/bin/bash
flow table bind --drop -c bind_client1_train_path.json
flow table bind --drop -c bind_client1_val_path.json
flow table bind --drop -c bind_client2_train_path.json
flow table bind --drop -c bind_client2_val_path.json
flow table bind --drop -c bind_client3_train_path.json
flow table bind --drop -c bind_client3_val_path.json
flow table bind --drop -c bind_client4_train_path.json
flow table bind --drop -c bind_client4_val_path.json
flow table bind --drop -c bind_client5_train_path.json
flow table bind --drop -c bind_client5_val_path.json
flow table bind --drop -c bind_client6_train_path.json
flow table bind --drop -c bind_client6_val_path.json
flow table bind --drop -c bind_client7_train_path.json
flow table bind --drop -c bind_client7_val_path.json
flow table bind --drop -c bind_client8_train_path.json
flow table bind --drop -c bind_client8_val_path.json
flow table bind --drop -c bind_client9_train_path.json
flow table bind --drop -c bind_client9_val_path.json
flow table bind --drop -c bind_client10_train_path.json
flow table bind --drop -c bind_client10_val_path.json
